@ReactApp1.Server_HostAddress = http://localhost:5282

GET {{ReactApp1.Server_HostAddress}}/user/
Accept: application/json

GET {{ReactApp1.Server_HostAddress}}/absence/
Accept: application/json

GET {{ReactApp1.Server_HostAddress}}/customer/
Accept: application/json

###
